// Static portfolio UI only. No endpoint, account, storage, or delivery service is configured.
module.exports = `<section class="section contact-form-section" id="contact-form"><div class="wrap contact-form-wrap"><div class="contact-form-head"><p class="eyebrow"><span>02</span>CONTACT FORM</p><h2 class="section-title"><span>お問い合わせ</span><span>フォーム</span></h2><p>こちらはポートフォリオ用のデモフォームです。<br>入力内容は送信・保存されません。</p></div>
<form class="demo-form" id="demo-contact" aria-describedby="demo-form-note" autocomplete="off">
<p id="demo-form-note" class="contact-demo-note">実際の個人情報は入力しないでください。入力内容は、このページを開いている間の確認表示にのみ使用します。</p>
<div class="contact-form-view" id="contact-input-view">
<fieldset disabled id="demo-fields"><legend class="visually-hidden">お問い合わせ内容の入力</legend>
<div class="form-row"><div class="form-field"><div class="form-label"><label for="inquiry-name">お名前</label><span class="form-status form-status--required">必須</span></div><input id="inquiry-name" type="text" maxlength="80" required placeholder="例）山田 太郎" autocomplete="name"></div><div class="form-field"><div class="form-label"><label for="inquiry-company">会社名</label><span class="form-status">任意</span></div><input id="inquiry-company" type="text" maxlength="120" placeholder="例）株式会社〇〇" autocomplete="organization"></div></div>
<div class="form-row"><div class="form-field"><div class="form-label"><label for="inquiry-email">メールアドレス</label><span class="form-status form-status--required">必須</span></div><input id="inquiry-email" type="email" maxlength="254" required placeholder="例）example@example.com" inputmode="email" autocomplete="email"></div><div class="form-field"><div class="form-label"><label for="inquiry-phone">電話番号</label><span class="form-status">任意</span></div><input id="inquiry-phone" type="tel" maxlength="30" placeholder="例）000-0000-0000" inputmode="tel" autocomplete="tel"></div></div>
<div class="form-field"><div class="form-label"><label for="inquiry-kind">お問い合わせ種別</label><span class="form-status form-status--required">必須</span></div><select id="inquiry-kind" required><option value="">選択してください</option><option>新築・建築工事について</option><option>改修・リノベーションについて</option><option>土木・外構工事について</option><option>採用について</option><option>その他</option></select></div>
<div class="form-field"><div class="form-label"><label for="inquiry-message">お問い合わせ内容</label><span class="form-status form-status--required">必須</span></div><textarea id="inquiry-message" rows="7" maxlength="3000" required placeholder="ご相談内容をご記入ください。"></textarea></div>
<div class="contact-form-action"><button class="button" type="submit" id="demo-confirm">入力内容を確認する <span aria-hidden="true">→</span></button></div>
</fieldset><noscript><p class="notice">フォームの操作にはJavaScriptが必要です。入力内容を送信する機能はありません。</p></noscript></div>
<section class="contact-confirm-view" id="contact-confirm-view" aria-labelledby="confirm-title" hidden><p class="eyebrow">CONFIRM</p><h3 id="confirm-title" tabindex="-1">入力内容の確認</h3><p>以下の内容でよろしければ、<br>「送信する」を押してください。</p><dl class="contact-confirm-list"><div><dt>お名前</dt><dd id="confirm-name"></dd></div><div><dt>会社名</dt><dd id="confirm-company"></dd></div><div><dt>メールアドレス</dt><dd id="confirm-email"></dd></div><div><dt>電話番号</dt><dd id="confirm-phone"></dd></div><div><dt>お問い合わせ種別</dt><dd id="confirm-kind"></dd></div><div><dt>お問い合わせ内容</dt><dd id="confirm-message"></dd></div></dl><div class="contact-confirm-actions"><button type="button" class="contact-back" id="demo-back">← 戻って修正する</button><button type="button" class="button" id="demo-send">送信する <span aria-hidden="true">→</span></button></div></section>
<section class="contact-complete-view" id="contact-complete-view" aria-labelledby="complete-title" hidden><p class="eyebrow">CONTACT COMPLETE</p><h3 id="complete-title" tabindex="-1">お問い合わせを<br>受け付けました。</h3><p>お問い合わせありがとうございます。</p><p>通常は内容を確認後、<br>担当者よりご連絡いたします。</p><aside><p>※このWebサイトはTUMIKI Web.の制作ポートフォリオとして制作した架空サイトです。<br>このお問い合わせフォームから実際に情報が送信されることはありません。</p></aside><a class="text-link" href="index.html">TOPページへ戻る <span class="arrow" aria-hidden="true">→</span></a></section>
</form></div></section>`;
